dist: xenial
sudo: true

language: python
python:
  - 3.7


before_install:
  - travis_retry bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh);
  - travis_retry pip install --upgrade pip setuptools wheel

install:
  - pip install ".[all]"

script:
  - py.test -vs -n auto --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml --doctest-modules pydra

after_script:
- codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER
