dist: xenial
sudo: true
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.7

env:
  global:
    - CHECK_TYPE="test"
    - INSTALL_TYPE="pip"
    - INSTALL_DEPENDS="pip setuptools"
  matrix:
    - INSTALL_TYPE="install"
    - INSTALL_TYPE="develop"
    - INSTALL_TYPE="sdist"
    - INSTALL_TYPE="wheel"
    - INSTALL_DEPENDS="pip==18.1 setuptools==30.2.1"
    - INSTALL_DEPENDS="pip==10.0.1 setuptools==30.3.0"
    - CHECK_TYPE="style"

# This should only fail with pip 10.0.1 with URL requirements (e.g., "package @ URL")
# Useful for testing un-released upstream fixes
matrix:
  allow_failures:
  - python: 3.7
    env: INSTALL_DEPENDS="pip==10.0.1 setuptools==30.3.0"


before_install:
  - travis_retry bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh);
  - travis_retry python -m pip install --upgrade $INSTALL_DEPENDS

install:
  - |
    if [ "$CHECK_TYPE" = "test" ]; then
        if [ "$INSTALL_TYPE" = "pip" ]; then
            pip install .
        elif [ "$INSTALL_TYPE" = "install" ]; then
            python setup.py install
        elif [ "$INSTALL_TYPE" = "develop" ]; then
            python setup.py develop
        elif [ "$INSTALL_TYPE" = "sdist" ]; then
            python setup.py sdist
            pip install dist/*.tar.gz
        elif [ "$INSTALL_TYPE" = "wheel" ]; then
            python setup.py bdist_wheel
            pip install dist/*.whl
        fi
        # Verify import with bare install
        python -c 'import pydra; print(pydra.__version__)'
    fi

before_script:
  - |
    if [ "$CHECK_TYPE" = "test" ]; then
        # Install test dependencies using similar methods...
        # Extras are interpreted by pip, not setup.py, so develop becomes editable
        # and install just becomes pip
        if [ "$INSTALL_TYPE" = "develop" ]; then
            pip install -e ".[test]"
        elif [ "$INSTALL_TYPE" = "sdist" ]; then
            pip install "$( ls dist/pydra*.tar.gz )[test]"
        elif [ "$INSTALL_TYPE" = "wheel" ]; then
            pip install "$( ls dist/pydra*.whl )[test]"
        else
            # extras don't seem possible with setup.py install, so switch to pip
            pip install ".[test]"
        fi
    elif [ "$CHECK_TYPE" = "style" ]; then
        pip install black
    fi

script:
  - |
    if [ "$CHECK_TYPE" = "test" ]; then
        py.test -vs -n auto --cov pydra/engine/tests/test_task.py --cov-config .coveragerc --cov-report xml:cov.xml --doctest-modules pydra
    elif [ "$CHECK_TYPE" = "style" ]; then
        black pydra setup.py
    fi

after_script:
- codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER
