dist: xenial
sudo: true
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.7
  - 3.8

services:
  - docker

env:
  global:
    - CHECK_TYPE="test"
    - INSTALL_TYPE="pip"
    - INSTALL_DEPENDS="pip setuptools"
    - JOBQUEUE="none"

  matrix:
    - INSTALL_TYPE="install"
    - INSTALL_TYPE="develop"
    - INSTALL_TYPE="sdist"
    - INSTALL_TYPE="wheel"
    - INSTALL_DEPENDS="pip==18.1 setuptools==30.2.1"
    - INSTALL_DEPENDS="pip==10.0.1 setuptools==30.3.0"
    - DEPENDS="-r min-requirements.txt"
    - CHECK_TYPE="style"

# This should only fail with pip 10.0.1 with URL requirements (e.g., "package @ URL")
# Useful for testing un-released upstream fixes
matrix:
  include:
  - python: 3.7
    env: JOBQUEUE="slurm"
  allow_failures:
  - python: 3.7
    env: INSTALL_DEPENDS="pip==10.0.1 setuptools==30.3.0"
  - python: 3.8
    env: INSTALL_DEPENDS="pip==10.0.1 setuptools==30.3.0"


before_install:
  - source ./ci/${JOBQUEUE}.sh
  - travis_before_install

install:
  - travis_install

before_script:
  - travis_before_script

script:
  - travis_script

after_script:
  - travis_after_script
