name: Dask Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-name:
          - test_boutiques
          - test_dockertask
          - test_graph
          - test_helpers
          - test_helpers_file
          - test_helpers_state
          - test_nipype1_convert
          - test_node_task
          - test_numpy_examples
          - test_profiles
          - test_shelltask
          - test_shelltask_inputspec
          - test_singularity
          - test_specs
          - test_state
          - test_submitter
          - test_task
          - test_tasks_files
          - test_workflow
      fail-fast: false

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Checkout Pydra repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Install pydra with Dask and test dependencies
        run: |
          pip install -e ".[test,dask]"

      - name: Run tests
        run: |
          pytest -v --dask pydra/engine/tests/${{ matrix.test-name }}.py --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml

      - name: Upload to codecov
        run: codecov -f cov.xml -F unittests -e GITHUB_WORKFLOW
