name: Singularity

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
      fail-fast: False

    steps:
      - name: Set env
        run: |
          echo "RELEASE_VERSION=v3.7.1" >> $GITHUB_ENV
          echo "NO_ET=TRUE" >> $GITHUB_ENV
      - name: Setup Singularity
        uses: actions/checkout@v4
        with:
          repository: hpcng/singularity
          ref: 'v3.7.1'
          path: 'singularity'
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '^1.13'
      - name: Install OS deps
        run: |
          sudo apt-get update
          sudo apt-get install flawfinder squashfs-tools uuid-dev libuuid1 libffi-dev libssl-dev libssl1.1 \
          libarchive-dev libgpgme11-dev libseccomp-dev wget gcc make pkg-config -y
      - name: Build
        run: |
          cd singularity
          ./mconfig --without-suid -p /usr/local/
          make -C ./builddir
          sudo make -C ./builddir install
          cd ..
      - name: Echo singularity version
        run: |
          echo ${{ github.ref }}
          singularity --version


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update build tools
        run: python -m pip install --upgrade pip


      - name: Checkout Pydra repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: Install pydra (test)
        run: pip install -e ".[test]"


      - name: Pytest
        run: pytest -vs --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml pydra/engine/tests/test_singularity.py
      - name: Upload to codecov
        run: codecov -f cov.xml -F unittests -e GITHUB_WORKFLOW
